@KanbanBoardBackendApi_HostAddress = http://localhost:5092

GET {{KanbanBoardBackendApi_HostAddress}}/api/Boards/
Accept: application/json

###
POST {{KanbanBoardBackendApi_HostAddress}}/api/Boards/
Content-Type: application/json

{
  "name": "test"
}