@startuml
'https://plantuml.com/deployment-diagram
skin rose

skinparam package {
  BackgroundColor white
}

rectangle "Domain Layer" #fcfdb9 {
    package "Domain" {
        [Entities]
    }
}

rectangle "Application Layer" #ffa09c {
    package "Application" {
        interface DrivenPorts
        [Use Cases]
        [DTOs]
    }
}

rectangle "Interface Adapters Layer" #a2fdba {
    package "API" {
        [Controllers]
        [Program]
    }
}

rectangle "Infrastructure Layer" #a7d7fd {
    package "Persistence.InMemory" {
        [InMemory\nRepositories]
    }
    package "Persistence.EFCore" {
            [EFCore\nRepositories]
    }
    package "Persistence.Proxy" {
                [Proxy\nRepositories]
    }
}

package "Tests" {
    [Integration Tests]
}

' Application depends on Domain
[Use Cases] ..> [Entities] : use

' API calls into Application Use Cases
[Controllers] --> [Use Cases] : call
[Controllers] ..> [DTOs] : send and receive

' Persistence implements abstractions defined in Domain/Application
[Proxy\nRepositories] ..> [Entities] : use
[Proxy\nRepositories] ..|> DrivenPorts : implement
[Proxy\nRepositories] -u-> [InMemory\nRepositories] : delegate on
[Proxy\nRepositories] -u-> [EFCore\nRepositories] : delegate on

' The Program (in API) wires up dependencies.
'[Program] --> [DrivenPorts]
'[Program] --> [Repositories]
'[Program] --> [Controllers]

' Integration tests interact with the entry point (API) to verify end-to-end flows
[Integration Tests] --> [Program] : exercise
[Integration Tests] ..> [Controllers] : simulate API calls
[Integration Tests] ..> [DTOs] : verify

@enduml



